In [48]:
#Dataframe manipulation 
import pandas as pd
import numpy as np

#NLTK library
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.tag import pos_tag

# country library
import pycountry

#plotting library
import matplotlib.pyplot as plt

In [2]:
#import csv
df_1 = pd.read_csv('articles_1.csv')
df_2 = pd.read_csv('articles_2.csv')

In [3]:
# concatenating the two dataframes
df = pd.concat([df_1, df_2], ignore_index=True)

In [6]:
#convert the data to datetime
df.article_date = pd.to_datetime(df.article_date)

In [7]:
#Select only the articles from 2019
df = df[(df['article_date'].dt.year == 2019)]

In [72]:
# Create a dataframe of only the articles  
df_articles = pd.DataFrame(df.article_body)

In [73]:
df_articles = df_articles.dropna(how='all')

In [80]:
# print(df.to_string())
for article in df_articles.article_body:
    article.to_string()

In [96]:
articles_list =  []
for article in df_articles.article_body:
    articles_list.append((word_tokenize(article)))

In [51]:
def preprocess(sent):
    sent = nltk.word_tokenize(sent)
    sent = nltk.pos_tag(sent)
    return sent

In [81]:
sent = preprocess(test)
print(sent)

[('0', 'CD'), ('Trina', 'NNP'), ('Solar', 'NNP'), ('recently', 'RB'), ('announced', 'VBD'), ('that', 'IN'), ('it', 'PRP'), ('has', 'VBZ'), ('beg', 'NN'), ('...', ':')]

In [63]:
print(articles_list[0:10])

NameError: name 'articles_list' is not defined

In [35]:
for index,title in zip(df.index,df.article_title):
    for country in pycountry.countries:
        if country.name in title:
            print(index,country.name)

6 Dominica
6 Dominican Republic
12 Germany
20 Japan
24 China
28 Ukraine
34 Brazil
35 India
39 Australia
54 India
55 Chile
56 France
64 Chile
66 India
75 Cayman Islands
77 Japan
80 Spain
80 India
81 India
82 Sweden
84 Jersey
85 Spain
96 Senegal
97 Netherlands
99 Italy
100 Mexico
103 Spain
106 Canada
109 Saudi Arabia
111 Jersey
114 Australia
115 India
117 India
118 Denmark
121 China
127 Germany
136 Australia
141 Australia
142 Brazil
143 Finland
143 Sweden
146 Spain
150 Sweden
152 Spain
152 Portugal
153 Jersey
156 Brazil
157 Rwanda
163 Norway
167 Qatar
170 Australia
178 Netherlands
179 Spain
184 Bangladesh
188 Maldives
192 Spain
197 Spain
204 Sweden
210 Greece
214 Japan
215 New Caledonia
216 Ireland
217 Malaysia
225 Australia
226 Canada
230 Canada
236 Iraq
240 China
241 Spain
245 Canada
255 Colombia
257 Italy
259 India
260 Brazil
262 Germany
264 Oman
268 India
271 Colombia
272 Benin
272 Kuwait
275 Peru
280 Egypt
282 France
292 Saudi Arabia
298 Chile
303 Oman
305 Kazakhstan
306 France
309 Kazakhstan
312 China
315 Brazil
324 India
327 Georgia
328 Belgium
329 Australia
332 China
338 Canada
340 India
347 Hungary
347 Poland
354 Canada
358 India
364 Oman
371 Australia
376 Spain
379 Finland
389 Portugal
393 Brazil
396 South Africa
421 Germany
429 Estonia
434 China
441 Canada
451 Chile
455 Jersey
464 Italy
465 South Africa
467 Thailand
469 Mexico
470 Togo
481 Georgia
484 Brazil
486 Egypt
493 India
495 Ukraine
496 Ukraine
501 Mexico
509 Mexico
510 Indonesia
520 Kazakhstan
530 Dominica
530 Dominican Republic
534 Finland
535 China
540 Canada
545 Australia
547 Ukraine
549 China
551 Spain
553 France
555 China
558 India
570 Iraq
573 Canada
576 Italy
579 Maldives
582 India
583 Australia
589 Panama
597 Switzerland
600 Australia
607 Chile
607 Peru
609 Antigua and Barbuda
610 China
612 Australia
614 Egypt
616 Cameroon
623 Japan
626 Germany
628 Ethiopia
629 Thailand
633 Argentina
641 Australia
648 Brazil
667 China
669 India
677 Bangladesh
678 Armenia
680 Belarus
684 Kazakhstan
689 Gambia
698 Chile
699 Netherlands
703 Spain
713 Italy
713 Luxembourg
720 Georgia
721 Netherlands
722 Colombia
727 India
728 Serbia
732 India
737 India
748 India
756 India
759 China
761 Australia
762 Australia
765 China
767 Bahamas
772 India
774 Pakistan
774 Tunisia
779 Italy
786 Greece
790 Australia
790 Tonga
791 Sweden
792 Norway
793 Myanmar
808 India
810 Norway
811 Albania
813 India
815 Netherlands
816 Bangladesh
818 Canada
820 Netherlands
829 Denmark
836 Netherlands
845 Morocco
847 Myanmar
851 France
852 Australia
859 Bangladesh
861 France
863 France
865 Brazil
866 Spain
875 Romania
877 Turkey
878 Argentina
878 Paraguay
882 Mongolia
882 Tonga
885 Egypt
887 India
890 India
893 India
895 Switzerland
902 Germany
906 China
912 Greece
919 Ecuador
921 China
922 Tajikistan
928 Brazil
932 Indonesia
934 Kenya
936 China
940 Tajikistan
943 Netherlands
950 Afghanistan
952 Sweden
953 Norway
956 Finland
961 Canada
973 France
974 China
983 China
992 Bangladesh
993 Pakistan
1001 Saudi Arabia
1004 Jersey
1006 Qatar
1007 Mexico
1009 Australia
1011 Denmark
1014 Brazil
1018 Kuwait
1018 Suriname
1020 Brazil
1023 Chile
1030 Italy
1039 Thailand
1040 Pakistan
1046 Argentina
1046 Australia
1049 Jordan
1057 China
1059 Spain
1060 Germany
1078 Zambia
1080 China
1080 Congo
1086 Mauritius
1088 Japan
1096 Brazil
1097 Australia
1107 Australia
1109 Mozambique
1115 Norway
1118 Colombia
1123 China
1128 Jersey
1136 Panama
1154 Sweden
1158 India
1166 China
1181 Canada
1188 Australia
1191 Norway
1192 Japan
1197 Belgium
1200 Denmark
1200 India
1201 Sweden
1209 Germany
1212 Kenya
1218 Israel
1221 Niger
1221 Nigeria
1228 Denmark
1228 India
1230 Canada
1230 Ukraine
1235 Serbia
1236 Canada
1237 Uzbekistan
1247 Japan
1250 Australia
1253 France
1254 India
1256 China
1257 Lithuania
1262 Japan
1263 Jersey
1271 Germany
1288 Egypt
1289 India
1290 Jordan
1291 Canada
1295 Brazil
1297 Sweden
1309 Brazil
1316 Kazakhstan
1320 Lesotho
1321 Zambia
1330 India
1332 China
1335 Belgium
1336 Ukraine
1338 Indonesia
1344 China
1345 Iraq
1350 Belgium
1355 Norway
1356 Thailand
1358 Costa Rica
1359 Poland
1364 Botswana
1365 Spain
1366 Mexico
1372 Ukraine
1381 Australia
1385 Spain
1388 Oman
1390 Tunisia
1392 Iraq
1395 Germany
1399 China
1414 Chile
1415 Italy
1416 Sudan
1417 Sweden
1422 Georgia
1430 Germany
1440 Norway
1441 Colombia
1447 Germany
1453 Pakistan
1458 New Zealand
1463 South Africa
1466 Brazil
1469 Jordan
1478 Malaysia
1484 Spain
1486 Oman
1494 Dominica
1496 Australia
1497 China
1499 Israel
1509 Namibia
1516 Norway
1533 Germany
1544 New Zealand
1547 Sweden
1554 Saudi Arabia
1556 Finland
1559 Uzbekistan
1561 Zambia
1566 Chile
1569 Afghanistan
1576 Botswana
1585 Morocco
1590 Australia
1591 Cambodia
1592 South Africa
1594 Italy
1597 Brazil
1603 Bermuda
1607 Egypt
1613 Poland
1614 Bangladesh
1615 Australia
1616 Germany
1618 Sweden
1622 South Africa
1625 China
1632 Japan
1636 Ukraine
1641 Ukraine
1651 Canada
1655 Indonesia
1657 China
1658 Angola
1662 Jersey
1664 Slovakia
1667 Japan
1670 France
1674 Spain
1677 Cyprus
1679 Argentina
1680 Belgium
1684 Ukraine
1685 Australia
1685 Chile
1690 Nepal
1691 Australia
1704 India
1706 Austria
1710 Georgia
1711 South Africa
1713 Portugal
1715 Egypt
1729 Belarus
1732 Spain
1734 Ukraine
1745 Kenya
1749 China
1751 China
1752 Niger
1752 Nigeria
1757 Namibia
1762 South Africa
1764 Sweden
1764 South Africa
1766 Namibia
1770 Chad
1771 Uganda
1774 Lesotho
1776 Ethiopia
1777 Rwanda
1778 South Africa
1781 South Africa
1788 Senegal
1790 Botswana
1791 Ethiopia
1795 Austria
1795 Japan
1796 South Africa
1798 Mauritania
1800 China
1809 Kenya
1811 Mauritius
1814 Ireland
1815 Niger
1815 Nigeria
1816 France
1821 Brazil
1823 China
1824 Niger
1824 Nigeria
1825 South Africa
1827 Mozambique
1832 Angola
1833 Niger
1833 Nigeria

In [40]:
print(df.article_title[300:325])

323    AltaGas completes $1.04bn stake sale in three ...
324    Siemens Gamesa wins orders for ReNew Power’s 5...
325    PowerOptions renews agreement with Solect Ener...
326    NextBridge secures right to build East-West Ti...
327    Georgia Power files 20-year plan to meet Georg...
328    Nemo Link interconnector between UK and Belgiu...
329    Lacour Energy’s Kondinin wind and solar farm s...
330    FPL begins operations of nearly 300MW solar pl...
331    Tekmar to provide cable protection for 219MW B...
332    INNIO to supply 3.35MW Jenbacher J620 gas engi...
333    Atlas Renewable Energy deploys NEXTracker’s Tr...
334    Hanergy to set up the region’s first thin-film...
335    How a stable salt reactor could solve nuclear ...
336    Thunder Bay Hydro and Kenora Hydro announce me...
337    Eaton to acquire controlling stake in Ulusoy E...
338    Budweiser Canada now brewed with 100% renewabl...
340    NIPSCO signs agreements for development of 800...
341    Harrison, Vickers & Waterman purchases remaini...
342    BlackRock Real Assets sells operating portfoli...
343    ABB to support the increasing digitalization o...
344                 Taiwan announces 2019 feed-in-tariff
345    ADB invests $20m in AC Energy climate bond to ...
346    Polish drone innovator flyMETRICS announces br...
347    ReneSola secures financing for wind projects i...
348    US DOE to offer $28m funding to advance offsho...
Name: article_title, dtype: object